### PR TITLE
Option to disable default vehicle commands

### PR DESCRIPTION
**Pull request by ESK0**
The reason is more or less simple, I believe a lot of servers use their own system to spawn vehicles that use identical 'car' and 'dv' commands

### CODE REVIEW

**Comment by thelindat** [comment]
Those servers aren't running ox_core and likely aren't using server-side handling though.

**Comment by ESK0** [comment]
For an example in my case.. I do use ox_core and I have my own commands for spawning/despawning and other vehicles related stuff outside of ox_core to keep the core as much custom changes free as possible.

**Comment by thelindat** [comment]
Won't your commands just override these anyway? Seems it makes little difference in the end. At the very least everything in ox_core needs to be moved to use require, and then just disable loading the module or return at the top of it rather than indent everything.

**Comment by ESK0** [comment]
I guess so, but to be honest I am not sure about this, if the command is overwritten or not

**Pull request closed without merging**
