### PR TITLE
Ox licenses

### PR DESCRIPTION
**Pull request by ESK0**
Modified data type from DATE to DATETIME
Fixed a few typos in text
Missing unique index for both licenses and statuses table

ontick adjusted to a maximum of 4 numbers with 3 decimal places for the following reason:
Maximum hunger value: 100
Minimum onTick value: 0.01
100 / 0.01 = 10000seconds = 166.6minutes

166 minutes is too short a time

### CODE REVIEW

**Comment by thelindat** [comment]
You added a way to suspend a license, but there would need to be a way to restore it (other than just removing and adding a new one). It may also be good if you could suspend it for a set amount of days, as an optional argument.

**Comment by ESK0** [comment]
> 

Well, that could be easily done with DATEDIFF. I could push this change tomorrow... I guess every server has a restart once in 24hrs so that should be totally good enough, Triggers requires a SUPER privilege that almost no one has except root users.

**Comment by thelindat** [comment]
> Triggers requires a SUPER privilege that almost no one has except root users

Was talking about an server event; but on the subject - I had to add a trigger to add new characters to the `character_inventory` table.. please tell me that's not going to cause a headache for people with weird setups.

**Comment by ESK0** [comment]
>  I had to add a trigger to add new characters to the `character_inventory`

People are stupid and mostly use root user or different user with root permissions. So there is a chance somebody will have an issue with the trigger

**Comment by ESK0** [comment]
If the decision was up to me.. I would definitely use INSERT ... ON DUPLICATE KEY UPDATE. instead of trigger.. or you do an insert after character creation

**Comment by ESK0** [comment]
> Was talking about a server event;

If I understand correctly... I would just recommend restart a server once in 24 hours instead of running an timer on a server side to check licenses. Ill do some changes tomorrow and you will decide.

**Comment by thelindat** [comment]
> If the decision was up to me.. I would definitely use INSERT ... ON DUPLICATE KEY UPDATE. instead of trigger.. or you do an insert after character creation

Character inventory should never need to insert though. I could insert it if select fails during setPlayerInventory but the new table feels meh. Especially if I redo inventory data in the future.

**Comment by ESK0** [comment]
> Character inventory should never need to insert though. I could insert it if select fails during setPlayerInventory but the new table feels meh. Especially if I redo inventory data in the future.

I see, wmhmhm, or just use transaction to substitute the trigger... I know it feels weird, but like this it should be faster when you read/write to characters table often.

**Pull request closed without merging**
